In [1]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [ ]:
#2. Print the numpy version and the configuration (★☆☆)
print('Version: ',np.__version__,'\n Configuration: ',np.__config__)

Version:  1.19.5 
 Configuration:  <module 'numpy.__config__' from '/usr/local/lib/python3.7/dist-packages/numpy/__config__.py'>


In [ ]:
#3. Create a null vector of size 10 (★☆☆)
null=np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4. How to find the memory size of any array (★☆☆)
null.size

10

In [ ]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null[4]=1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#8. Reverse a vector (first element becomes last) (★☆☆)
a=a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)¶
m=np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4]),)


In [ ]:
#11. Create a 3x3 identity matrix (★☆☆)
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#12. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))

array([[[0.8388692 , 0.75015912, 0.9943441 ],
        [0.9779621 , 0.13373409, 0.59321632],
        [0.75116334, 0.77423271, 0.20764199]],

       [[0.85943264, 0.17843988, 0.1714752 ],
        [0.45700779, 0.80379047, 0.42877211],
        [0.81922746, 0.8346857 , 0.29349931]],

       [[0.39624101, 0.44115985, 0.70787031],
        [0.48252556, 0.51427106, 0.82209154],
        [0.30574838, 0.24969927, 0.57607737]]])

In [ ]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.0355814248024936 0.9851960200717097


In [ ]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
a=np.random.random(30)
print(a.mean())

0.5015111595041152


In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
m=np.ones((10,10))
m[1:-1,1:-1]=0
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
x = np.ones((10,10))
m = np.pad(array=x, pad_width=1, mode='constant')
print(m)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#17. What is the result of the following expression? (★☆☆)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
m=np.zeros((8,8))
m[1::2,1::2]=6
m[::2,::2]=6
print(m)

[[6. 0. 6. 0. 6. 0. 6. 0.]
 [0. 6. 0. 6. 0. 6. 0. 6.]
 [6. 0. 6. 0. 6. 0. 6. 0.]
 [0. 6. 0. 6. 0. 6. 0. 6.]
 [6. 0. 6. 0. 6. 0. 6. 0.]
 [0. 6. 0. 6. 0. 6. 0. 6.]
 [6. 0. 6. 0. 6. 0. 6. 0.]
 [0. 6. 0. 6. 0. 6. 0. 6.]]


In [ ]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
amini=np.array([[0,1], [1,0]])
m=np.tile(amini,(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#22. Normalize a 5x5 random matrix (★☆☆)
m=np.random.random((5,5))
m=(m-m.min())/(m.max()-m.min())
print(m)

[[0.886088   0.93748343 0.57226555 0.70442122 0.42289082]
 [0.91286216 0.22633614 0.82623189 0.59703279 0.2059449 ]
 [0.9944156  0.07921649 0.         0.93874084 0.2494308 ]
 [0.56307318 0.78753102 1.         0.3311151  0.46133723]
 [0.02147908 0.68592975 0.8152518  0.33544615 0.72967964]]


In [ ]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


In [ ]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
m=np.dot(np.ones((5,3)), np.ones((3,2)))
print(m)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
a=np.ones(12)
a[2:8]*=-1
print(a)

[ 1.  1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1.]


In [ ]:
#26. What is the output of the following script?
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal?
z=np.array([1,2,4])
print(z**z,2<<z>>2,z<-z,1j*z,z/1/1)
#illegal: z<z>z

[  1   4 256] [1 2 8] [False False False] [0.+1.j 0.+2.j 0.+4.j] [1. 2. 4.]


In [ ]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

In [ ]:
#29. How to round away from zero a float array ?
a=np.array([1.2,1.56,6.32,4.83,9.05,6,-1.1,-2])
print(np.round(a,0))

[ 1.  2.  6.  5.  9.  6. -1. -2.]


In [ ]:
#30. How to find common values between two arrays?
a=np.array([1,2,4,3])
b=np.array([2,3,4,1])
a==b

array([False, False,  True, False])

In [ ]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)
#i choose not to ignore the warning as recommended! #sanity_still_intact!

In [ ]:
#32. Is the following expressions true? (★☆☆) 
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [ ]:
#33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
today = np.datetime64('today', 'D')
yesterday = today - np.datetime64(1, 'D')
print(today)

2021-09-03


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)¶
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
x = np.random.uniform(-5, +5, 10)
x.astype(np.int32)
np.trunc(x)

array([ 2.,  2.,  3.,  3., -0., -4.,  0.,  0.,  2.,  1.])

In [ ]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
x = np.zeros((5, 5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
#40. Create a random vector of size 10 and sort it (★★☆)
x = np.random.random(10)
x.sort()
print(x)

[0.01716118 0.11855641 0.18858116 0.28106875 0.35908391 0.67441465
 0.73398763 0.73703488 0.92115549 0.98255347]


In [ ]:
#41. How to sum a small array faster than np.sum? (★★☆)
import time

begin_time = time.time()
x = np.arange(1000000)
np.sum(x)
end_time = time.time()
print(str(1000*(end_time - begin_time)))

begin_time2 = time.time()
x = np.arange(1000000)
np.add.reduce(x)
end_time2 = time.time()
print(str(1000*(end_time2 - begin_time2)))

6.577968597412109
2.6998519897460938


In [ ]:
#42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.random(10)
B = np.random.random(10)
np.array_equal(A, B)

False

In [ ]:
#43. Make an array immutable (read-only) (★★☆)
x = np.zeros(10)
x.flags.writeable = False
x[1] = 1

ValueError: ignored

In [ ]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[1.14572072 0.86645065 1.1741913  0.12823141 0.29392535 1.08751217
 0.10852725 0.84115831 0.97055338 0.60953312]
[0.80075823 0.03183454 0.6866672  1.1536346  1.22177053 0.75425556
 0.50433281 1.21828931 1.43939823 0.43642251]


In [ ]:
# 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
x = np.random.random(10)
x[x == np.max(x)] = 0
print(x)

[0.81525483 0.         0.23889835 0.22655167 0.18040853 0.5884372
 0.80416013 0.96380275 0.79463755 0.71497102]


In [ ]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[-5.64701726e+05,  1.93650936e+05, -5.35915386e+06,
         2.52171821e+05, -1.02932565e+08],
       [ 8.66982023e+07,  8.69371680e+05,  2.03999960e+08,
        -5.00678828e+04,  2.30623595e+05],
       [ 2.07356467e+05, -1.94620121e+06, -5.38030918e+03,
        -1.31074632e+04,  8.54820828e+05],
       [-1.03179854e+06,  8.67091738e+05,  1.19563815e+05,
         1.24207581e+05,  8.54447607e+05],
       [-6.97226969e+05,  6.25546244e+03, -4.02814121e+07,
         5.36558042e+06,  1.30511001e+06]])

In [ ]:
#48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)



-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#49. How to print all the values of an array? (★★☆)
Z = np.zeros((5,5))
print(Z)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z,v,Z[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 2.9630171455634513 3


In [ ]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

Z = np.zeros(10, [ ('position', [ ('x', float),
                                   ('y', float)]),
                    ('color',    [ ('r', float),
                                   ('g', float),
                                   ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.52681773 0.70164408 0.15947856 0.70270248 0.49528
  0.2892171  0.51313373 0.32904762 0.21947086]
 [0.52681773 0.         0.27185988 0.53144884 0.41754305 0.33029537
  0.29935816 0.72430483 0.5585785  0.43921374]
 [0.70164408 0.27185988 0.         0.75294868 0.20207451 0.27562646
  0.54551287 0.70174198 0.59652111 0.53750677]
 [0.15947856 0.53144884 0.75294868 0.         0.792919   0.59243669
  0.23979058 0.67119852 0.48244604 0.35435475]
 [0.70270248 0.41754305 0.20207451 0.792919   0.         0.20784358
  0.62803874 0.55971107 0.50539794 0.49977542]
 [0.49528    0.33029537 0.27562646 0.59243669 0.20784358 0.
  0.45357385 0.43231118 0.32323921 0.29329739]
 [0.2892171  0.29935816 0.54551287 0.23979058 0.62803874 0.45357385
  0.         0.68818934 0.49008051 0.33762695]
 [0.51313373 0.72430483 0.70174198 0.67119852 0.55971107 0.43231118
  0.68818934 0.         0.19904357 0.35111558]
 [0.32904762 0.5585785  0.59652111 0.48244604 0.50539794 0.32323921
  0.49008051 0.19904357

In [ ]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [88]:
#54. How to read the following file? (★★☆) 
#obviously im using colab so i cant read it -_-
Z = np.genfromtxt("missing.dat", delimiter=",")

OSError: ignored

In [ ]:
#55 .What is the equivalent of enumerate for numpy arrays ? (★★☆)
Z = np.arange(9).reshape(3,3)

for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [3]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x**2+y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [4]:
#57. How to randomly place p elements in a 2D array? (★★☆)
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
#58. Subtract the mean of each row of a matrix (★★☆)
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)


[[ 0.22678399 -0.12190283 -0.28164248  0.14752198 -0.1896997   0.23062739
   0.15885632  0.38268156 -0.37287523 -0.18035101]
 [-0.4458718   0.38974255  0.10587996  0.07160116  0.25992319 -0.49565844
  -0.16989465  0.24752393 -0.20299386  0.23974797]
 [-0.34897786  0.30217677 -0.02326    -0.08217037 -0.05446726  0.25491391
   0.19229835 -0.17570436  0.4048082  -0.46961739]
 [-0.02045817  0.25832298  0.41491726 -0.44235725  0.28466137 -0.45625612
   0.30437719 -0.12212014  0.22380365 -0.44489075]
 [-0.16263884 -0.36202376  0.41471718 -0.15093888 -0.33437355 -0.27308437
  -0.22619061  0.12076835  0.57719432  0.39657016]]


In [8]:
#59. How to sort an array by the nth column? (★★☆)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 6 0]
 [6 2 1]
 [9 7 3]]
[[6 2 1]
 [2 6 0]
 [9 7 3]]


In [9]:
#60. How to tell if a given 2D array has null columns? (★★☆)
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [10]:
#61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.564213778177486


In [22]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
a=np.random.randint(0,10,(1,3))
b=np.random.randint(0,10,(3,1))

g=np.nditer([a,b,None])
for x,y,z in g: 
  z[...] = x + y
print(a,b,g.operands[2])

[[3 6 1]] [[8]
 [4]
 [6]] [[11 14  9]
 [ 7 10  5]
 [ 9 12  7]]


In [87]:
#63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):

  def __new__(cls, array, name="no name"):

    obj = np.asarray(array).view(cls)

    obj.name = name

    return obj

    def __array_finalize__(self, obj):

      if obj is None: 
        return

    self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")

print (Z.name)

range_10


In [26]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1. 5. 3. 1. 7. 2. 3. 3. 3. 2.]


In [15]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [16]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [29]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 44 66 64]
 [50 38 64 52]
 [61 47 63 65]]


In [30]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.47244527 0.53557773 0.51903411 0.33834835 0.47647549 0.63473284
 0.38183171 0.53510794 0.33619241 0.5139478 ]


In [32]:
#69. How to get the diagonal of a dot product? (★★★)
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.sum(A*B.T,axis=1)

array([120,  18,   1])

In [33]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [37]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [38]:
#72. How to swap two rows of an array? (★★★)
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [39]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 44) ( 0, 92) ( 4, 15) ( 4, 37) (10, 17) (10, 51) (11, 43) (11, 49)
 (15, 17) (15, 24) (15, 37) (17, 24) (17, 51) (25, 61) (25, 66) (28, 44)
 (28, 60) (36, 58) (36, 83) (42, 79) (42, 97) (43, 49) (44, 60) (44, 92)
 (58, 83) (60, 72) (60, 83) (61, 66) (72, 83) (79, 97)]


In [40]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [41]:
#75. How to compute averages using a sliding window over an array? (★★★)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [42]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [43]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))


Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 1 0 1
 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0 1
 1 0 1 0 0 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 0]
Negating a boolean: 
[0 0 0 0 0 0 1 1 0 1 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0
 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 1 1 0
 0 1 0 1 1 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1]
original: 
[-0.97446999 -0.06579633  0.85755148 -0.21048824 -0.86458545  0.93842887
  0.75030498  0.32013318 -0.35837332  0.79334878]
Change the sign of float inplace: 
[ 0.97446999  0.06579633 -0.85755148  0.21048824  0.86458545 -0.93842887
 -0.75030498 -0.32013318  0.35837332 -0.79334878]


In [44]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.03408913 12.97454595 10.98056636 13.41949011  4.22343625 15.76792268
  6.24602296  6.08983476  3.49959318  3.31357255]


In [45]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.22747918  7.6710224   2.05412327  7.77273809  8.37578074]
 [ 3.56895953  7.04319499  0.5354508   6.85817313  4.75640317]
 [ 3.68574918  1.22755931  8.39199741  1.12029589  2.01787462]
 [ 9.36239975  5.16314862  0.23869928  6.08937608 12.23412186]
 [ 2.84114237 10.82340265 11.78883783 11.03519285  8.42763193]]


In [46]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 7 3 4 6 9 9 3 8 3]
 [9 4 0 1 2 9 2 1 5 2]
 [4 7 3 0 7 5 0 9 7 7]
 [0 8 8 8 1 3 3 7 2 9]
 [3 8 4 2 6 0 9 1 7 4]
 [8 8 5 5 3 1 1 2 7 4]
 [8 4 1 9 5 6 5 2 1 2]
 [1 7 1 8 7 2 1 6 8 9]
 [0 3 5 8 1 4 0 5 0 9]
 [1 8 3 2 9 4 9 0 0 3]]
[[0 0 0 0 0]
 [0 6 7 3 4]
 [0 9 4 0 1]
 [0 4 7 3 0]
 [0 0 8 8 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [47]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [49]:
#82. Compute a matrix rank (★★★)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [50]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[9 8 2 4 4 7 7 9 8 9 2 7 9 2 7 7 6 0 9 7 5 4 6 3 9 9 2 0 0 3 0 8 1 9 7 1 1
 1 4 8 6 6 7 6 0 1 3 8 2 0]
rank: 7


In [51]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

Z = np.random.randint(0,5,(6,6))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 3 2]
   [4 1 0]
   [1 2 3]]

  [[3 2 1]
   [1 0 4]
   [2 3 2]]

  [[2 1 4]
   [0 4 0]
   [3 2 4]]

  [[1 4 4]
   [4 0 1]
   [2 4 4]]]


 [[[4 1 0]
   [1 2 3]
   [0 2 1]]

  [[1 0 4]
   [2 3 2]
   [2 1 3]]

  [[0 4 0]
   [3 2 4]
   [1 3 4]]

  [[4 0 1]
   [2 4 4]
   [3 4 1]]]


 [[[1 2 3]
   [0 2 1]
   [3 0 1]]

  [[2 3 2]
   [2 1 3]
   [0 1 3]]

  [[3 2 4]
   [1 3 4]
   [1 3 0]]

  [[2 4 4]
   [3 4 1]
   [3 0 4]]]


 [[[0 2 1]
   [3 0 1]
   [3 4 3]]

  [[2 1 3]
   [0 1 3]
   [4 3 1]]

  [[1 3 4]
   [1 3 0]
   [3 1 0]]

  [[3 4 1]
   [3 0 4]
   [1 0 0]]]]


In [54]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
      i,j=index
      super(Symetric, self).__setitem__((i,j), value)
      super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  5  6  5 11]
 [ 5  2  9  9  6]
 [ 6  9  1 42  7]
 [ 5  9 42  9  2]
 [11  6  7  2  3]]


In [55]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [56]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [57]:
#88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

In [58]:
#89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


In [59]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [62]:
#91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [66]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
x = np.random.rand(5*10^7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

The slowest run took 11.13 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.39 µs per loop
The slowest run took 14.76 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.16 µs per loop
The slowest run took 19.78 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.07 µs per loop


In [67]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[1 3 4 5 7]


In [68]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 2 3]
 [2 2 4]
 [1 2 3]
 [3 1 4]
 [0 3 2]
 [2 0 0]
 [0 3 3]
 [2 4 4]
 [0 2 4]
 [4 0 0]]
[[4 2 3]
 [2 2 4]
 [1 2 3]
 [3 1 4]
 [0 3 2]
 [2 0 0]
 [0 3 3]
 [2 4 4]
 [0 2 4]
 [4 0 0]]


In [69]:
#95. Convert a vector of ints into a matrix binary representation (★★★)
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [70]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 1]]


In [86]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

A= np.arange(3)
B =  np.arange(12).reshape(3,4)
print(A)

#https://ajcr.net/Basic-guide-to-einsum/
#Dunno why it not works... its the same as in the website...

np.einsum('i->', A) # np.sum(A)

np.einsum('i,i->i', A, B) # A * B

np.einsum('i,i', A, B) # np.inner(A, B)

np.einsum('i,j', A, B) # np.outer(A, B

[0 1 2]


ValueError: ignored

In [75]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print(r_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

In [76]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],[2.0, 0.0, 1.0, 1.0],[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [77]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.236068    0.15360639]
